spring:
  application:
    name: cinema-tickets
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
#Logging properties
Logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
  path: ${LOG_FOLDER:${user.home}/logs}

# You can override the values with environment variables
server:
  port: ${SERVER_PORT:9030}
  servlet:
    context-path: ${CONTEXT_PATH:/cinema-reservation}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-alias: ${KEY_ALIAS:service}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-store: ${KEYSTORE_LOCATION:classpath:keystore.jks}
    key-store-type: JKS

# You can override the messages with environment variables
cinemaTickets:
  issuingParty:
    name: third-party

  validation:
    noOfTickets:
      allowed: ${CINEMA_TICKETS_VALIDATION_NO_OF_TICKETS_ALLOWED:22}
      error: ${CINEMA_TICKETS_VALIDATION_NO_OF_TICKETS_ERROR:You cannot purchase more than %d tickets}
    adultPresence:
      error: ${CINEMA_TICKETS_VALIDATION_ADULT_PRESENCE_ERROR:You cannot book Child/Infant ticket without Adult ticket}
  prices:
    INFANT: ${CINEMA_TICKETS_PRICES_INFANT:0}
    CHILD: ${CINEMA_TICKETS_PRICES_CHILD:10}
    ADULT: ${CINEMA_TICKETS_PRICES_ADULT:20}